SET IDENTITY_INSERT [etl].[ControlTable_Ingest_dataverse] ON 
GO
INSERT [etl].[ControlTable_Ingest_dataverse] ([id], [SourceExtractMethod], [ObjectTypeCode], [DataverseSourceEntity], [DeltaWatermarkColumnName], [DeltaLastWatermarkDateTimeUTC], [StageSchema], [TargetType], [TargetServer], [TargetDatabase], [TargetSchema], [TargetTable], [TargetKeyColumn], [PreCopyScript], [IsActiveFlag], [PipelineLastRunDateTimeUTC], [PipelineRunId], [PipelineTriggerName], [LastRunStatus]) VALUES (1, N'FULL', 1, N'account', NULL, CAST(N'2024-10-29T21:48:49.0000000' AS DateTime2), N'stg', N'Azure SQL', N'jdobbins-sql.database.windows.net', N'dobbins', N'dbo', N'account_full', N'accountid', N'', 1, CAST(N'2024-10-29T21:48:47.4700000' AS DateTime2), N'ee8c2ace-230f-4d50-a526-ba103748b452', N'Sandbox', N'Success')
GO
INSERT [etl].[ControlTable_Ingest_dataverse] ([id], [SourceExtractMethod], [ObjectTypeCode], [DataverseSourceEntity], [DeltaWatermarkColumnName], [DeltaLastWatermarkDateTimeUTC], [StageSchema], [TargetType], [TargetServer], [TargetDatabase], [TargetSchema], [TargetTable], [TargetKeyColumn], [PreCopyScript], [IsActiveFlag], [PipelineLastRunDateTimeUTC], [PipelineRunId], [PipelineTriggerName], [LastRunStatus]) VALUES (2, N'DELTA', 1, N'account', N'modifiedon', CAST(N'2024-10-29T21:48:49.0000000' AS DateTime2), N'stg', N'Azure SQL', N'jdobbins-sql.database.windows.net', N'dobbins', N'dbo', N'account_delta', N'accountid', NULL, 1, CAST(N'2024-10-29T21:48:47.4700000' AS DateTime2), N'ee8c2ace-230f-4d50-a526-ba103748b452', N'Sandbox', N'Success')
GO
INSERT [etl].[ControlTable_Ingest_dataverse] ([id], [SourceExtractMethod], [ObjectTypeCode], [DataverseSourceEntity], [DeltaWatermarkColumnName], [DeltaLastWatermarkDateTimeUTC], [StageSchema], [TargetType], [TargetServer], [TargetDatabase], [TargetSchema], [TargetTable], [TargetKeyColumn], [PreCopyScript], [IsActiveFlag], [PipelineLastRunDateTimeUTC], [PipelineRunId], [PipelineTriggerName], [LastRunStatus]) VALUES (3, N'FULL', 1, N'account', NULL, CAST(N'2024-10-29T21:46:52.6000000' AS DateTime2), N'stg', N'Azure SQL', N'jdobbins-sql.database.windows.net', N'dobbins', N'dbo', N'account_delta', N'accountid', NULL, 0, CAST(N'2024-10-29T21:46:19.6500000' AS DateTime2), N'a65d368f-78e6-4930-aff3-a59a31e9e1f0', N'Sandbox', N'Success')
GO
INSERT [etl].[ControlTable_Ingest_dataverse] ([id], [SourceExtractMethod], [ObjectTypeCode], [DataverseSourceEntity], [DeltaWatermarkColumnName], [DeltaLastWatermarkDateTimeUTC], [StageSchema], [TargetType], [TargetServer], [TargetDatabase], [TargetSchema], [TargetTable], [TargetKeyColumn], [PreCopyScript], [IsActiveFlag], [PipelineLastRunDateTimeUTC], [PipelineRunId], [PipelineTriggerName], [LastRunStatus]) VALUES (4, N'FULL', 2, N'contact', N'modifiedon', CAST(N'2024-10-29T21:46:50.7066667' AS DateTime2), N'stg', N'Azure SQL', N'jdobbins-sql.database.windows.net', N'dobbins', N'dbo', N'contact', N'contactid', NULL, 0, CAST(N'2024-10-29T21:46:19.6500000' AS DateTime2), N'a65d368f-78e6-4930-aff3-a59a31e9e1f0', N'Sandbox', N'Success')
GO
INSERT [etl].[ControlTable_Ingest_dataverse] ([id], [SourceExtractMethod], [ObjectTypeCode], [DataverseSourceEntity], [DeltaWatermarkColumnName], [DeltaLastWatermarkDateTimeUTC], [StageSchema], [TargetType], [TargetServer], [TargetDatabase], [TargetSchema], [TargetTable], [TargetKeyColumn], [PreCopyScript], [IsActiveFlag], [PipelineLastRunDateTimeUTC], [PipelineRunId], [PipelineTriggerName], [LastRunStatus]) VALUES (5, N'DELTA', 2, N'contact', N'modifiedon', CAST(N'2024-10-29T21:48:49.0000000' AS DateTime2), N'stg', N'Azure SQL', N'jdobbins-sql.database.windows.net', N'dobbins', N'dbo', N'contact', N'contactid', NULL, 1, CAST(N'2024-10-29T21:48:47.4700000' AS DateTime2), N'ee8c2ace-230f-4d50-a526-ba103748b452', N'Sandbox', N'Success')
GO
SET IDENTITY_INSERT [etl].[ControlTable_Ingest_dataverse] OFF
GO
